import type { Metadata } from "next";
import { Inter, Manrope, } from 'next/font/google'
import "./globals.css";
import StateContextProvider from "../app/context";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope',
  display: 'swap',
})




export const metadata: Metadata = {
  title: "FutureLabs",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${manrope.variable}  font-sans max-w-[1440px] mx-auto  w-full `}>
        <StateContextProvider>
          {children}
        </StateContextProvider>

      </body>
    </html>
  );
}